# Generated by Django 4.2.18 on 2025-02-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
