name: Docker Image CI third

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run server
      run: docker-compose up -d
    - name: run tests
      run: docker-compose exec web sh -c "flake8 && pytest ."
